[package]
name = "emupc-rs"
version = "0.1.0"
authors = ["qeeg"]
license = "BSD-3-Clause"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.1.0"